package com.zwn.model;

import java.util.Date;

public class Comment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.cid
     *
     * @mbggenerated
     */
    private Integer cid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.ccontent
     *
     * @mbggenerated
     */
    private String ccontent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.date
     *
     * @mbggenerated
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.uid
     *
     * @mbggenerated
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.miid
     *
     * @mbggenerated
     */
    private Integer miid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.likesnum
     *
     * @mbggenerated
     */
    private Integer likesnum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.cid
     *
     * @return the value of comment.cid
     *
     * @mbggenerated
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.cid
     *
     * @param cid the value for comment.cid
     *
     * @mbggenerated
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.ccontent
     *
     * @return the value of comment.ccontent
     *
     * @mbggenerated
     */
    public String getCcontent() {
        return ccontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.ccontent
     *
     * @param ccontent the value for comment.ccontent
     *
     * @mbggenerated
     */
    public void setCcontent(String ccontent) {
        this.ccontent = ccontent == null ? null : ccontent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.date
     *
     * @return the value of comment.date
     *
     * @mbggenerated
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.date
     *
     * @param date the value for comment.date
     *
     * @mbggenerated
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.uid
     *
     * @return the value of comment.uid
     *
     * @mbggenerated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.uid
     *
     * @param uid the value for comment.uid
     *
     * @mbggenerated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.miid
     *
     * @return the value of comment.miid
     *
     * @mbggenerated
     */
    public Integer getMiid() {
        return miid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.miid
     *
     * @param miid the value for comment.miid
     *
     * @mbggenerated
     */
    public void setMiid(Integer miid) {
        this.miid = miid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.likesnum
     *
     * @return the value of comment.likesnum
     *
     * @mbggenerated
     */
    public Integer getLikesnum() {
        return likesnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.likesnum
     *
     * @param likesnum the value for comment.likesnum
     *
     * @mbggenerated
     */
    public void setLikesnum(Integer likesnum) {
        this.likesnum = likesnum;
    }
}