package com.zwn.model;

public class Fans {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fans.fid
     *
     * @mbggenerated
     */
    private Integer fid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fans.follow
     *
     * @mbggenerated
     */
    private Integer follow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fans.uid
     *
     * @mbggenerated
     */
    private Integer uid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fans.fid
     *
     * @return the value of fans.fid
     *
     * @mbggenerated
     */
    public Integer getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fans.fid
     *
     * @param fid the value for fans.fid
     *
     * @mbggenerated
     */
    public void setFid(Integer fid) {
        this.fid = fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fans.follow
     *
     * @return the value of fans.follow
     *
     * @mbggenerated
     */
    public Integer getFollow() {
        return follow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fans.follow
     *
     * @param follow the value for fans.follow
     *
     * @mbggenerated
     */
    public void setFollow(Integer follow) {
        this.follow = follow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fans.uid
     *
     * @return the value of fans.uid
     *
     * @mbggenerated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fans.uid
     *
     * @param uid the value for fans.uid
     *
     * @mbggenerated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }
}