package com.zwn.model;

public class Integralmall {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column integralmall.imid
     *
     * @mbggenerated
     */
    private Integer imid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column integralmall.imname
     *
     * @mbggenerated
     */
    private String imname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column integralmall.imvarchar
     *
     * @mbggenerated
     */
    private String imvarchar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column integralmall.imscore
     *
     * @mbggenerated
     */
    private Integer imscore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column integralmall.imimage
     *
     * @mbggenerated
     */
    private String imimage;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column integralmall.imid
     *
     * @return the value of integralmall.imid
     *
     * @mbggenerated
     */
    public Integer getImid() {
        return imid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column integralmall.imid
     *
     * @param imid the value for integralmall.imid
     *
     * @mbggenerated
     */
    public void setImid(Integer imid) {
        this.imid = imid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column integralmall.imname
     *
     * @return the value of integralmall.imname
     *
     * @mbggenerated
     */
    public String getImname() {
        return imname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column integralmall.imname
     *
     * @param imname the value for integralmall.imname
     *
     * @mbggenerated
     */
    public void setImname(String imname) {
        this.imname = imname == null ? null : imname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column integralmall.imvarchar
     *
     * @return the value of integralmall.imvarchar
     *
     * @mbggenerated
     */
    public String getImvarchar() {
        return imvarchar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column integralmall.imvarchar
     *
     * @param imvarchar the value for integralmall.imvarchar
     *
     * @mbggenerated
     */
    public void setImvarchar(String imvarchar) {
        this.imvarchar = imvarchar == null ? null : imvarchar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column integralmall.imscore
     *
     * @return the value of integralmall.imscore
     *
     * @mbggenerated
     */
    public Integer getImscore() {
        return imscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column integralmall.imscore
     *
     * @param imscore the value for integralmall.imscore
     *
     * @mbggenerated
     */
    public void setImscore(Integer imscore) {
        this.imscore = imscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column integralmall.imimage
     *
     * @return the value of integralmall.imimage
     *
     * @mbggenerated
     */
    public String getImimage() {
        return imimage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column integralmall.imimage
     *
     * @param imimage the value for integralmall.imimage
     *
     * @mbggenerated
     */
    public void setImimage(String imimage) {
        this.imimage = imimage == null ? null : imimage.trim();
    }
}