package com.zwn.model;

import java.util.Date;

public class Movieinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movieinfo.miid
     *
     * @mbggenerated
     */
    private Integer miid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movieinfo.image
     *
     * @mbggenerated
     */
    private String image;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movieinfo.mname
     *
     * @mbggenerated
     */
    private String mname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movieinfo.mplot
     *
     * @mbggenerated
     */
    private String mplot;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movieinfo.mdirector
     *
     * @mbggenerated
     */
    private String mdirector;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movieinfo.mactor
     *
     * @mbggenerated
     */
    private String mactor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movieinfo.mdate
     *
     * @mbggenerated
     */
    private String mdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movieinfo.maudit
     *
     * @mbggenerated
     */
    private Integer maudit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movieinfo.uid
     *
     * @mbggenerated
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movieinfo.aid
     *
     * @mbggenerated
     */
    private Integer aid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movieinfo.mtid
     *
     * @mbggenerated
     */
    private Integer mtid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movieinfo.date
     *
     * @mbggenerated
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movieinfo.average
     *
     * @mbggenerated
     */
    private Double average;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movieinfo.shtg
     *
     * @mbggenerated
     */
    private Integer shtg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movieinfo.miid
     *
     * @return the value of movieinfo.miid
     *
     * @mbggenerated
     */
    public Integer getMiid() {
        return miid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movieinfo.miid
     *
     * @param miid the value for movieinfo.miid
     *
     * @mbggenerated
     */
    public void setMiid(Integer miid) {
        this.miid = miid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movieinfo.image
     *
     * @return the value of movieinfo.image
     *
     * @mbggenerated
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movieinfo.image
     *
     * @param image the value for movieinfo.image
     *
     * @mbggenerated
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movieinfo.mname
     *
     * @return the value of movieinfo.mname
     *
     * @mbggenerated
     */
    public String getMname() {
        return mname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movieinfo.mname
     *
     * @param mname the value for movieinfo.mname
     *
     * @mbggenerated
     */
    public void setMname(String mname) {
        this.mname = mname == null ? null : mname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movieinfo.mplot
     *
     * @return the value of movieinfo.mplot
     *
     * @mbggenerated
     */
    public String getMplot() {
        return mplot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movieinfo.mplot
     *
     * @param mplot the value for movieinfo.mplot
     *
     * @mbggenerated
     */
    public void setMplot(String mplot) {
        this.mplot = mplot == null ? null : mplot.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movieinfo.mdirector
     *
     * @return the value of movieinfo.mdirector
     *
     * @mbggenerated
     */
    public String getMdirector() {
        return mdirector;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movieinfo.mdirector
     *
     * @param mdirector the value for movieinfo.mdirector
     *
     * @mbggenerated
     */
    public void setMdirector(String mdirector) {
        this.mdirector = mdirector == null ? null : mdirector.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movieinfo.mactor
     *
     * @return the value of movieinfo.mactor
     *
     * @mbggenerated
     */
    public String getMactor() {
        return mactor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movieinfo.mactor
     *
     * @param mactor the value for movieinfo.mactor
     *
     * @mbggenerated
     */
    public void setMactor(String mactor) {
        this.mactor = mactor == null ? null : mactor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movieinfo.mdate
     *
     * @return the value of movieinfo.mdate
     *
     * @mbggenerated
     */
    public String getMdate() {
        return mdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movieinfo.mdate
     *
     * @param mdate the value for movieinfo.mdate
     *
     * @mbggenerated
     */
    public void setMdate(String mdate) {
        this.mdate = mdate == null ? null : mdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movieinfo.maudit
     *
     * @return the value of movieinfo.maudit
     *
     * @mbggenerated
     */
    public Integer getMaudit() {
        return maudit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movieinfo.maudit
     *
     * @param maudit the value for movieinfo.maudit
     *
     * @mbggenerated
     */
    public void setMaudit(Integer maudit) {
        this.maudit = maudit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movieinfo.uid
     *
     * @return the value of movieinfo.uid
     *
     * @mbggenerated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movieinfo.uid
     *
     * @param uid the value for movieinfo.uid
     *
     * @mbggenerated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movieinfo.aid
     *
     * @return the value of movieinfo.aid
     *
     * @mbggenerated
     */
    public Integer getAid() {
        return aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movieinfo.aid
     *
     * @param aid the value for movieinfo.aid
     *
     * @mbggenerated
     */
    public void setAid(Integer aid) {
        this.aid = aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movieinfo.mtid
     *
     * @return the value of movieinfo.mtid
     *
     * @mbggenerated
     */
    public Integer getMtid() {
        return mtid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movieinfo.mtid
     *
     * @param mtid the value for movieinfo.mtid
     *
     * @mbggenerated
     */
    public void setMtid(Integer mtid) {
        this.mtid = mtid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movieinfo.date
     *
     * @return the value of movieinfo.date
     *
     * @mbggenerated
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movieinfo.date
     *
     * @param date the value for movieinfo.date
     *
     * @mbggenerated
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movieinfo.average
     *
     * @return the value of movieinfo.average
     *
     * @mbggenerated
     */
    public Double getAverage() {
        return average;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movieinfo.average
     *
     * @param average the value for movieinfo.average
     *
     * @mbggenerated
     */
    public void setAverage(Double average) {
        this.average = average;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movieinfo.shtg
     *
     * @return the value of movieinfo.shtg
     *
     * @mbggenerated
     */
    public Integer getShtg() {
        return shtg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movieinfo.shtg
     *
     * @param shtg the value for movieinfo.shtg
     *
     * @mbggenerated
     */
    public void setShtg(Integer shtg) {
        this.shtg = shtg;
    }
}