package com.zwn.model;

import java.util.Date;

public class Movienew {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movienew.mnid
     *
     * @mbggenerated
     */
    private Integer mnid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movienew.mntital
     *
     * @mbggenerated
     */
    private String mntital;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movienew.mnvarchar
     *
     * @mbggenerated
     */
    private String mnvarchar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movienew.date
     *
     * @mbggenerated
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movienew.aid
     *
     * @mbggenerated
     */
    private Integer aid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movienew.image
     *
     * @mbggenerated
     */
    private String image;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movienew.mnid
     *
     * @return the value of movienew.mnid
     *
     * @mbggenerated
     */
    public Integer getMnid() {
        return mnid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movienew.mnid
     *
     * @param mnid the value for movienew.mnid
     *
     * @mbggenerated
     */
    public void setMnid(Integer mnid) {
        this.mnid = mnid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movienew.mntital
     *
     * @return the value of movienew.mntital
     *
     * @mbggenerated
     */
    public String getMntital() {
        return mntital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movienew.mntital
     *
     * @param mntital the value for movienew.mntital
     *
     * @mbggenerated
     */
    public void setMntital(String mntital) {
        this.mntital = mntital == null ? null : mntital.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movienew.mnvarchar
     *
     * @return the value of movienew.mnvarchar
     *
     * @mbggenerated
     */
    public String getMnvarchar() {
        return mnvarchar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movienew.mnvarchar
     *
     * @param mnvarchar the value for movienew.mnvarchar
     *
     * @mbggenerated
     */
    public void setMnvarchar(String mnvarchar) {
        this.mnvarchar = mnvarchar == null ? null : mnvarchar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movienew.date
     *
     * @return the value of movienew.date
     *
     * @mbggenerated
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movienew.date
     *
     * @param date the value for movienew.date
     *
     * @mbggenerated
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movienew.aid
     *
     * @return the value of movienew.aid
     *
     * @mbggenerated
     */
    public Integer getAid() {
        return aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movienew.aid
     *
     * @param aid the value for movienew.aid
     *
     * @mbggenerated
     */
    public void setAid(Integer aid) {
        this.aid = aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movienew.image
     *
     * @return the value of movienew.image
     *
     * @mbggenerated
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movienew.image
     *
     * @param image the value for movienew.image
     *
     * @mbggenerated
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }
}