package com.zwn.model;

public class Moviescore {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column moviescore.sid
     *
     * @mbggenerated
     */
    private Integer sid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column moviescore.uid
     *
     * @mbggenerated
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column moviescore.score
     *
     * @mbggenerated
     */
    private Integer score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column moviescore.miid
     *
     * @mbggenerated
     */
    private Integer miid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column moviescore.sid
     *
     * @return the value of moviescore.sid
     *
     * @mbggenerated
     */
    public Integer getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column moviescore.sid
     *
     * @param sid the value for moviescore.sid
     *
     * @mbggenerated
     */
    public void setSid(Integer sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column moviescore.uid
     *
     * @return the value of moviescore.uid
     *
     * @mbggenerated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column moviescore.uid
     *
     * @param uid the value for moviescore.uid
     *
     * @mbggenerated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column moviescore.score
     *
     * @return the value of moviescore.score
     *
     * @mbggenerated
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column moviescore.score
     *
     * @param score the value for moviescore.score
     *
     * @mbggenerated
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column moviescore.miid
     *
     * @return the value of moviescore.miid
     *
     * @mbggenerated
     */
    public Integer getMiid() {
        return miid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column moviescore.miid
     *
     * @param miid the value for moviescore.miid
     *
     * @mbggenerated
     */
    public void setMiid(Integer miid) {
        this.miid = miid;
    }
}