package com.zwn.model;

public class Scoreorder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scoreorder.omid
     *
     * @mbggenerated
     */
    private Integer omid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scoreorder.score
     *
     * @mbggenerated
     */
    private Integer score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scoreorder.imid
     *
     * @mbggenerated
     */
    private Integer imid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scoreorder.uid
     *
     * @mbggenerated
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scoreorder.state
     *
     * @mbggenerated
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scoreorder.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scoreorder.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scoreorder.addr
     *
     * @mbggenerated
     */
    private String addr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scoreorder.date
     *
     * @mbggenerated
     */
    private String date;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scoreorder.omid
     *
     * @return the value of scoreorder.omid
     *
     * @mbggenerated
     */
    public Integer getOmid() {
        return omid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scoreorder.omid
     *
     * @param omid the value for scoreorder.omid
     *
     * @mbggenerated
     */
    public void setOmid(Integer omid) {
        this.omid = omid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scoreorder.score
     *
     * @return the value of scoreorder.score
     *
     * @mbggenerated
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scoreorder.score
     *
     * @param score the value for scoreorder.score
     *
     * @mbggenerated
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scoreorder.imid
     *
     * @return the value of scoreorder.imid
     *
     * @mbggenerated
     */
    public Integer getImid() {
        return imid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scoreorder.imid
     *
     * @param imid the value for scoreorder.imid
     *
     * @mbggenerated
     */
    public void setImid(Integer imid) {
        this.imid = imid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scoreorder.uid
     *
     * @return the value of scoreorder.uid
     *
     * @mbggenerated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scoreorder.uid
     *
     * @param uid the value for scoreorder.uid
     *
     * @mbggenerated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scoreorder.state
     *
     * @return the value of scoreorder.state
     *
     * @mbggenerated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scoreorder.state
     *
     * @param state the value for scoreorder.state
     *
     * @mbggenerated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scoreorder.name
     *
     * @return the value of scoreorder.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scoreorder.name
     *
     * @param name the value for scoreorder.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scoreorder.phone
     *
     * @return the value of scoreorder.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scoreorder.phone
     *
     * @param phone the value for scoreorder.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scoreorder.addr
     *
     * @return the value of scoreorder.addr
     *
     * @mbggenerated
     */
    public String getAddr() {
        return addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scoreorder.addr
     *
     * @param addr the value for scoreorder.addr
     *
     * @mbggenerated
     */
    public void setAddr(String addr) {
        this.addr = addr == null ? null : addr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scoreorder.date
     *
     * @return the value of scoreorder.date
     *
     * @mbggenerated
     */
    public String getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scoreorder.date
     *
     * @param date the value for scoreorder.date
     *
     * @mbggenerated
     */
    public void setDate(String date) {
        this.date = date == null ? null : date.trim();
    }
}