package com.zwn.dao;

import com.zwn.model.Integralmall;

public interface IntegralmallMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table integralmall
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer imid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table integralmall
     *
     * @mbggenerated
     */
    int insert(Integralmall record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table integralmall
     *
     * @mbggenerated
     */
    int insertSelective(Integralmall record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table integralmall
     *
     * @mbggenerated
     */
    Integralmall selectByPrimaryKey(Integer imid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table integralmall
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Integralmall record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table integralmall
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Integralmall record);
}