package com.zwn.dao;

import com.zwn.model.Movieinfo;

public interface MovieinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movieinfo
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer miid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movieinfo
     *
     * @mbggenerated
     */
    int insert(Movieinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movieinfo
     *
     * @mbggenerated
     */
    int insertSelective(Movieinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movieinfo
     *
     * @mbggenerated
     */
    Movieinfo selectByPrimaryKey(Integer miid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movieinfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Movieinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movieinfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Movieinfo record);
}