package com.zwn.dao;

import com.zwn.model.Movienew;

public interface MovienewMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movienew
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer mnid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movienew
     *
     * @mbggenerated
     */
    int insert(Movienew record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movienew
     *
     * @mbggenerated
     */
    int insertSelective(Movienew record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movienew
     *
     * @mbggenerated
     */
    Movienew selectByPrimaryKey(Integer mnid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movienew
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Movienew record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movienew
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Movienew record);
}