package com.zwn.dao;

import com.zwn.model.Movietype;

public interface MovietypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movietype
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer mtid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movietype
     *
     * @mbggenerated
     */
    int insert(Movietype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movietype
     *
     * @mbggenerated
     */
    int insertSelective(Movietype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movietype
     *
     * @mbggenerated
     */
    Movietype selectByPrimaryKey(Integer mtid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movietype
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Movietype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movietype
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Movietype record);
}