package com.zwn.dao;

import com.zwn.model.Moviescore;

public interface MoviescoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moviescore
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moviescore
     *
     * @mbggenerated
     */
    int insert(Moviescore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moviescore
     *
     * @mbggenerated
     */
    int insertSelective(Moviescore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moviescore
     *
     * @mbggenerated
     */
    Moviescore selectByPrimaryKey(Integer sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moviescore
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Moviescore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moviescore
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Moviescore record);
}